### ISSUE TITLE
Convert backend to Java, can leverage Spring Cloud

### ISSUE THREAD

**Issue by sladyn98** [jay24rajput/Visirion-Bot#11]
@av06 @jay24rajput @MANOJ-OCHANEY Consider switching the backend to spring Boot in java giving us a micro service capability like
a) Service for rebasing repos
b) Service for adding labels to issues
c) Marking issues as stale
d) Closing issues
e) Fast Forwarding issues

We can use Spring Cloud for cloud based operations.

**Comment by jay24rajput** [comment]
@sladyn98 The migration will be easy since there is not many things that the Django server is doing. But is there not any substitute to Sprong Cloud in python for any python frameworks??
